export const productsSeed = [
    { name: 'Paracetamol 500mg', active_principle: 'Paracetamol', stock: 100, price: 2.50, alert_threshold: 20 },
    { name: 'Ibuprofeno 400mg', active_principle: 'Ibuprofeno', stock: 80, price: 3.00, alert_threshold: 15 },
    { name: 'Amoxicilina 500mg', active_principle: 'Amoxicilina', stock: 50, price: 5.50, alert_threshold: 10 },
    { name: 'Loratadina 10mg', active_principle: 'Loratadina', stock: 60, price: 4.00, alert_threshold: 15 },
    { name: 'Omeprazol 20mg', active_principle: 'Omeprazol', stock: 120, price: 6.00, alert_threshold: 25 },
    { name: 'Aspirina 100mg', active_principle: 'Ácido Acetilsalicílico', stock: 200, price: 1.50, alert_threshold: 30 },
    { name: 'Diclofenaco 50mg', active_principle: 'Diclofenaco', stock: 40, price: 3.50, alert_threshold: 10 },
    { name: 'Cetirizina 10mg', active_principle: 'Cetirizina', stock: 75, price: 4.50, alert_threshold: 15 },
    { name: 'Azitromicina 500mg', active_principle: 'Azitromicina', stock: 30, price: 8.00, alert_threshold: 5 },
    { name: 'Losartán 50mg', active_principle: 'Losartán', stock: 90, price: 7.00, alert_threshold: 20 },
    { name: 'Metformina 850mg', active_principle: 'Metformina', stock: 150, price: 4.00, alert_threshold: 30 },
    { name: 'Salbutamol Inhalador', active_principle: 'Salbutamol', stock: 25, price: 9.00, alert_threshold: 5 },
    { name: 'Clonazepam 2mg', active_principle: 'Clonazepam', stock: 20, price: 12.00, alert_threshold: 5 },
    { name: 'Fluconazol 150mg', active_principle: 'Fluconazol', stock: 45, price: 5.00, alert_threshold: 10 },
    { name: 'Pantoprazol 40mg', active_principle: 'Pantoprazol', stock: 65, price: 7.50, alert_threshold: 15 },
    { name: 'Tramadol 50mg', active_principle: 'Tramadol', stock: 35, price: 6.50, alert_threshold: 10 },
    { name: 'Ciprofloxacino 500mg', active_principle: 'Ciprofloxacino', stock: 40, price: 6.00, alert_threshold: 10 },
    { name: 'Enalapril 10mg', active_principle: 'Enalapril', stock: 110, price: 3.00, alert_threshold: 20 },
    { name: 'Levotiroxina 100mcg', active_principle: 'Levotiroxina', stock: 85, price: 5.50, alert_threshold: 15 },
    { name: 'Atorvastatina 20mg', active_principle: 'Atorvastatina', stock: 95, price: 8.50, alert_threshold: 20 },
    { name: 'Diazepam 5mg', active_principle: 'Diazepam', stock: 15, price: 4.00, alert_threshold: 5 },
    { name: 'Domperidona 10mg', active_principle: 'Domperidona', stock: 55, price: 3.50, alert_threshold: 10 },
    { name: 'Metoclopramida 10mg', active_principle: 'Metoclopramida', stock: 50, price: 2.50, alert_threshold: 10 },
    { name: 'Naproxeno 500mg', active_principle: 'Naproxeno', stock: 70, price: 4.50, alert_threshold: 15 },
    { name: 'Ketorolaco 10mg', active_principle: 'Ketorolaco', stock: 60, price: 3.50, alert_threshold: 10 },
    { name: 'Prednisona 5mg', active_principle: 'Prednisona', stock: 80, price: 5.00, alert_threshold: 15 },
    { name: 'Dexametasona 4mg', active_principle: 'Dexametasona', stock: 45, price: 2.00, alert_threshold: 10 },
    { name: 'Vitamina C 1g', active_principle: 'Ácido Ascórbico', stock: 200, price: 2.00, alert_threshold: 40 },
    { name: 'Complejo B', active_principle: 'Vitaminas B', stock: 150, price: 3.50, alert_threshold: 30 },
    { name: 'Melatonina 3mg', active_principle: 'Melatonina', stock: 40, price: 6.50, alert_threshold: 10 }
];